### PR TITLE
Remove external kubernetes proxy mode

### PR DESCRIPTION
**Pull request by sttts**
Proxy mode was deprecated in 3.5 and will be removed for 3.6.

### CODE REVIEW

**Comment by deads2k** [comment]
@sttts can we get just that last commit and merge it separately or do you want to wait on everything?

**Comment by sttts** [comment]
@deads2k this will be the baseline for the rebase. Why do you want to merge that separately?

**Comment by sttts** [comment]
Note that the PR is against mfojtik:apigroups. It only diverted.

**Comment by deads2k** [comment]
> @deads2k this will be the baseline for the rebase. Why do you want to merge that separately?

According to @bparees, the queue is open for 3.6 work.  We know we want to remove the proxy, I'd take the incremental progress.

**Pull request closed without merging**
